# Generated by Django 4.0.6 on 2022-09-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='Interviewer',
            new_name='interviewer',
        ),
    ]
