# Generated by Django 4.0.6 on 2022-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_interviewer_interview_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='linkedin_address',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
