# Generated by Django 4.0.6 on 2022-09-05 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=100)),
                ('status', models.CharField(choices=[('phone', 'phone'), ('code', 'code'), ('technical', 'technical'), ('final', 'final')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('pending', 'pending'), ('Approved to Interview', 'Approved to Interview'), ('being interviewed', 'being interviewed'), ('Approved for Hire', 'Approved for Hire'), ('rejected', 'rejected')], max_length=100)),
                ('Interviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement.interviewer')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.interview')),
            ],
        ),
    ]
